"""fix relationships

Revision ID: 3a4df88442b5
Revises: c0f431ac6f50
Create Date: 2022-04-24 04:07:21.925534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a4df88442b5'
down_revision = 'c0f431ac6f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
