"""fix currencies

Revision ID: 44d2f5501815
Revises: 3a4df88442b5
Create Date: 2022-04-24 08:58:27.128708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d2f5501815'
down_revision = '3a4df88442b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currencies_name', table_name='currencies')
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.create_index('ix_currencies_name', 'currencies', ['name'], unique=False)
    # ### end Alembic commands ###
