"""add NewsBooks table

Revision ID: c0f431ac6f50
Revises: 28ebe6bb6ec0
Create Date: 2022-04-24 03:35:02.192861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f431ac6f50'
down_revision = '28ebe6bb6ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_books_id'), 'news_books', ['id'], unique=True)
    op.create_table('users_news_books',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('news_book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_book_id'], ['news_books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_news_books')
    op.drop_index(op.f('ix_news_books_id'), table_name='news_books')
    op.drop_table('news_books')
    # ### end Alembic commands ###
